* STADGAR FÖR IT-Gården
med hemort i Växjö stad

Bildad 2018

ALLMÄNNA BESTÄMMELSER

** 1 §    Ändamål
 Föreningen har som ändamål att bedriva ideell verksamhet i form av en fritidsgård med IT (Internet Technology) inriktning. Med särskild målsättning att skapa en plats för unga och studerande att utvecklas, ha roligt och samtidigt förbereda sig inför arbetslivet inom IT. Föreningen vänder sig till människor i alla åldrar, oavsett bakgrund. Föreningen ska aktivt arbeta för att motverka all form av diskriminering.

** 2 §    Sammansättning
 Föreningen består av de fysiska personer som har upptagits i föreningen som medlemmar.

** 3 §    Beslutande organ
 Föreningens beslutande organ är årsmöte, extra årsmöte och styrelsen.

** 4 §   Föreningensteckning
 Föreningen tecknas av styrelsen eller, om styrelsen så beslutar, av två styrelseledamöter gemensamt varav en ska vara ordförande eller vice ordförande.

** 5 §    Verksamhets- och räkenskapsår
 Föreningens verksamhetsår och räkenskapsår är 1 januari - 31 december.

** 6 §    Stadgetolkning
 Uppstår tvekan om tolkningen av dessa stadgar, eller om fall förekommer som inte är förutsedda i stadgarna, hänskjuts frågan till nästkommande årsmöte. I brådskande fall får frågan avgöras av styrelsen.

** 7 §    Skiljeklausul
 Talan i tvist mellan medlem och föreningen får inte väckas vid allmän domstol. Sådan tvist skall, utom i fall då annan särskild ordning är föreskriven, avgöras enligt lagen om skiljeförfarande. Dock skall följande gälla rörande kostnaderna för skiljeförfarandet. Vardera parten svarar för egna kostnader liksom för kostnaderna för den skiljeman man utsett. Kostnaderna för ordförande och sekreterare, delas lika mellan parterna.

** 8 §    Stadgeändring
 För ändring av dessa stadgar krävs beslut på två på varandra följande möten, med minst en månads mellanrum, varav ett ska vara årsmöte, med minst 2/3 av antalet avgivna röster.
 Förslag till ändring av stadgarna får skriftligen avges av såväl medlem som styrelsen.

** 9 §    Upplösning av föreningen
 För upplösning av föreningen krävs beslut på två på varandra följande möten, med minst en månads mellanrum, varav ett ska vara årsmöte, med minst 2/3 av antalet avgivna röster. I beslut om upplösning av föreningen skall föreningens tillgångar skänkas till Allmänna Arvsfonden och föreningens handlingar m.m. skall arkiveras på Stadsarkivet.

 FÖRENINGENS MEDLEMMAR

** 10 §    Medlemskap
 Förening är öppen för alla fysiska personer. Medlem skall följa föreningens stadgar och föreskrifter. När medlemsavgiften är erlagd är personen medlem och förs in i medlemsförteckningen. Styrelsen har rätt att utse person till hedersmedlem.

** 11 §    Utträde
 Medlem som vill utträda ur föreningen, skall skriftligen anmäla detta till styrelsen och anses därmed omedelbart ha lämnat föreningen. Medlem som inte har betalat medlemsavgift senast den 31 december får anses ha begärt sitt utträde ur föreningen. Medlemskapet upphör i sådant fall genom att personen avförs från medlemsförteckningen.

** 12 §    Uteslutning
 Medlem får inte uteslutas ur föreningen av annan anledning än att denne har försummat att betala av föreningen beslutade avgifter, motarbetat föreningens verksamhet eller ändamål, eller uppenbarligen skadat föreningens intressen. Beslut om uteslutning eller varning får inte fattas utan att medlemmen inom viss tid, minst 14 dagar, fått tillfälle att yttra sig över de omständigheter som föranlett att medlemskapet ifrågasätts. I beslutet skall skälen härför redovisas samt anges vad medlemmen skall iaktta för överklagande. Beslutet skall inom tre dagar från dagen för beslutet skriftligen meddelas den berörde.

** 13 §    Medlems rättigheter och skyldigheter
 Medlem
 • har rätt att delta i sammankomster som anordnas för medlemmarna
 • har rätt till information om föreningens angelägenheter
 • skall följa föreningens stadgar samt beslut som fattats av föreningsorgan
 • har inte rätt till del av föreningens behållning eller egendom vid upplösning av föreningen
 • skall betala medlemsavgift samt eventuellt övriga avgifter som beslutats av föreningen

 ÅRSMÖTE och EXTRA ÅRSMÖTE

** 14 §    Tidpunkt, kallelse
 Årsmötet, som är föreningens högsta beslutande organ, hålls före utgången av mars månad på tid och plats som styrelsen bestämmer. Kallelse till årsmötet skall av styrelsen senast tre veckor före mötet tillställas medlemmarna på följande sätt; via mail, anslås i klubblokalen, i föreningens facebook grupp och på hemsidan. Har förslag väckts om stadgeändring, nedläggning eller sammanslagning av föreningen med annan förening eller annan fråga av väsentlig betydelse för föreningen eller dess medlemmar skall det anges i kallelsen. Verksamhets- och förvaltningsberättelser, revisorernas berättelser, verksamhetsplan med budget samt styrelsens förslag och inkomna motioner med styrelsens yttrande skall finnas tillgängliga för medlemmarna senast en vecka före årsmötet. I kallelsen skall anges var dessa handlingar finns tillgängliga.

** 15 §    Förslag till motioner att behandlas av årsmöte
 Såväl medlem som styrelsen får avge förslag att behandlas av årsmöte. Förslag från medlem skall vara styrelsen tillhanda senast två veckor före årsmötet. Styrelsen skall till årsmötet avge skriftligt yttrande över förslaget.

** 16 §    Rösträtt samt yttrande- och förslagsrätt
 Medlem som har betalt medlemsavgiften senast 30 dagar före mötet och under mötesåret fyller lägst 12 år har rösträtt på möte. Rösträtten är personlig och får inte utövas genom ombud. Medlem som inte har rösträtt har yttrande- och förslagsrätt på mötet.

** 17 §    Beslutsförhet
 Mötet är beslutsmässigt med det antal röstberättigade medlemmar som är närvarande på mötet.

** 18 §    Beslut och omröstning
 Beslut fattas med bifallsrop (acklamation) eller om så begärs efter omröstning (votering).
 Med undantag för de i 8 § och 9 § nämnda fallen avgörs vid omröstning alla frågor genom enkel majoritet. Enkel majoritet kan vara antingen absolut eller relativ. Val avgörs genom relativ majoritet. Med relativ majoritet menas att den (de) som erhållit högsta antalet röster är vald (valda) oberoende av hur dessa röster förhåller sig till antalet avgivna röster. För beslut i andra frågor än val krävs absolut majoritet, vilket innebär mer än hälften av antalet avgivna röster. Omröstning sker öppet. Om röstberättigad medlem begär det skall dock val ske slutet. Vid omröstning som inte avser val gäller vid lika röstetal det förslag som biträds av ordföranden vid mötet, om ordföranden är röstberättigad. Är ordförande inte röstberättigad avgör lotten. Vid val skall i händelse av lika röstetal lotten avgöra. Beslut bekräftas med klubbslag.

** 19 §    Valbarhet
 Valbar till styrelsen och valberedningen är röstberättigad medlem av föreningen.

** 20 §    Ärenden vid årsmötet
 Vid årsmötet skall följande behandlas och protokollföras:
 1.   Fastställande av röstlängd för mötet (vem som har rösträtt).
 2.   Val av ordförande och sekreterare för mötet.
 3.   Val av protokolljusterare och rösträknare.
 4.   Val av justeringsmän
 5.   Fråga om mötet har utlysts på rätt sätt.
 6.   Fastställande av dagordning.
 7.   a) Styrelsens verksamhetsberättelse för det senaste verksamhetsåret.
      b) Styrelsens förvaltningsberättelse (balans- och resultaträkning) för det senaste räkenskapsåret.
 8.   Fastställande av verksamhetsplan samt behandling av budget för det kommande verksamhets-/räkenskapsåret.
 9.   Val av föreningens ordförande.
 10.  Val av revisor
 11.  Val av valberedning
 12.  Handläggning av förslag från styrelsen
 13.  Handläggning av förslag från föreningsmedlem

** 21 §    Extra årsmöte
 Styrelsen kan kalla medlemmarna till extra årsmöte. Styrelsen är skyldig att kalla till extra årsmöte när minst 20 % av föreningens röstberättigade medlemmar begär det. Sådan framställning skall göras skriftligen till styrelsen och innehålla skälen för begäran.
 När styrelsen mottagit en begäran om extra årsmöte skall den inom 14 dagar utlysa sådant möte att hållas inom två månader från erhållen begäran. Kallelse med förslag till föredragningslista för extra årsmöte skall tillställas medlemmarna senast sju dagar före mötet på det sätt styrelsen bestämt. Vidare skall kallelsen med förslag till föredragningslista publiceras på föreningens hemsida, anslås i föreningens lokal eller på annan lämplig plats. Underlåter styrelsen att utlysa eller kalla till extra årsmöte får de som gjort framställningen vidta åtgärder enligt föregående stycke. Vid extra årsmöte får endast det som föranlett mötet upptas till behandling. Om rösträtt på extra årsmöte och om beslutsmässighet vid sådant möte gäller vad som sägs i 16 § och 17 §.

 VALBEREDNINGEN

** 22 §	Sammansättning, åligganden
 Valberedningen består av en till tre ledamöter, varav en sammankallande, valda av årsmötet. Valberedningen sammanträder när ordföranden eller minst halva antalet ledamöter så bestämmer. Valberedningen skall senast 2 veckor före årsmötet tillfråga dem vilkas mandattid utgår vid mötets slut, om de vill kandidera för nästa mandattid. Senast 1 veckor före årsmötet skall valberedningen meddela röstberättigade medlemmar sitt förslag.

 REVISORER

** 23 §    Revision
 En revisor skall väljas på årsmötet som ska granska föreningens verksamhet. Revisorn ska agera både sak- och siffer revisor. Revisorn skall vara myndig och får ej vara jävig.

 STYRELSEN

** 24 §    Sammansättning
 Styrelsen består av ordförande samt 2-6 övriga ledamöter. Styrelsen bör bestå av kvinnor och män. Styrelsen utser inom sig vice ordförande, kassör och övriga befattningshavare som behövs.

** 25 §    Styrelsens åligganden
 När årsmöte inte är samlat är styrelsen föreningens beslutande organ och ansvarar för föreningens angelägenheter. Styrelsen skall - inom ramen för dessa stadgar - svara för föreningens verksamhet enligt fastställda planer samt tillvarata medlemmarnas intressen.
 Det åligger styrelsen särskilt att
 •    tillse att för föreningen gällande lagar och bindande regler iakttas
 •    verkställa av årsmötet fattade beslut
 •    planera, leda och fördela arbetet inom föreningen
 •    ansvara för och förvalta föreningens medel
 •    tillställa revisorerna räkenskaper för det gångna räkenskapsåret.
 •    förbereda årsmöte

** 26 §    Kallelse, beslutsmässighet och omröstning
 Styrelsen sammanträder efter kallelse av ordföranden, eller då minst halva antalet ledamöter har begärt det. Styrelsen är beslutsmässig när samtliga ledamöter kallats och då minst halva antalet ledamöter är närvarande. För alla beslut krävs att minst hälften av styrelsens samtliga ledamöter är ense om beslutet. Vid lika röstetal har ordföranden utslagsröst. Röstning får inte ske genom ombud. I brådskande fall får ordföranden besluta att ärende skall avgöras genom skriftlig omröstning eller annan typ av elekroniskt sammanträde. Om särskilt protokoll inte upprättas skall sådant beslut anmälas vid det närmast därefter följande sammanträdet. Vid sammanträde skall protokoll föras. Protokoll skall justeras av mötesordföranden. Avvikande mening skall antecknas till protokollet.

** 27 §    Överlåtelse av beslutanderätten
 Styrelsen får överlåta sin beslutanderätt i enskilda ärenden eller i vissa grupper av ärenden till sektion, kommitté eller annat organ eller till enskild medlem eller anställd. Den som fattat beslut med stöd av bemyndigande skall fortlöpande underrätta styrelsen härom.
