# Table of contents
#+OPTIONS: toc:nil

# Section numbering
#+OPTIONS: num:nil

# Number of headings to export
#+OPTIONS: H:4

# Disable super/subscripting
#+OPTIONS: ^:nil

* Kallelse och dagordning årsmöte

Kallelse till årsmöte för IT-Gården. \\
Datum: 2018-12-12 \\
Tid: 17:00 (Efter vårt möte med "fritidsgårdsfolket") \\
Plats: Teknikum \\

** § 1 Mötets Öppnande
Mötet öppnades.

** § 2 Val av mötesordförande
Marcus Mueller väljs som mötesordförande.

** § 3 Val av mötessekreterare
Marcus Mueller väljs som mötessekreterare.

** § 4 Val av justeringsperson
Fartun Jama väljs som justeringsperson.

** § 5 Godkännande av dagordning
Dagordning godkänns av alla.

** § 6 Fastställande av röstlängd
Närvarande personer räknas och röstlängd fastställs till sju.

** § 7 Årsmötets behöriga utlysande 
Godkänns av alla.

** § 8 Verksamhetsberättelse och ekonomisk berättelse
Alla går med på att skippa denna punkt eftersom det inte finns något tidigare att redovisa.

** § 9 Behandling av inkomna motioner och styrelsens förslag
Inga tillkomna motioner, endast rättstavning av Haneen's namn. Upplagt förslag för val av styrelse roller godkänns av alla.

** § 10 Val av ordförande (President)
Marcus valdes

** § 11 Val av vice ordförande (Vice President)
Cristian Babes valdes

** § 12 Val av kassör (Treasurer)
Haneen Mohialdeen valdes

** § 13 Val av övriga ledamöter (Other board members)
Daniel Lundberg, Amata Anantaprayoon och Fartun Jama valdes

** § 14 Val av revisor (Audior)
Amata Anantaprayoon valdes

** § 15 Val av valberedning (Election Committee)
Fartun Jama och Daniel Lundberg valdes

** § 16 Mötets avslutande
Mötet avslutades

** Mötesordförande


----------------------------------------------


** Mötessekreterare


----------------------------------------------


** Justeringsperson


----------------------------------------------
